// <auto-generated />
using System;
using ConnectingDotsAPI.DBModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConnectingDotsAPI.Migrations
{
    [DbContext(typeof(ConnectingDotsDbContext))]
    partial class ConnectingDotsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityLogTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityLogTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLog", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.ActivityLogType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SystemKeyword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogType", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasColumnType("longtext");

                    b.Property<string>("Address2")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Company")
                        .HasColumnType("longtext");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("County")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomAttributes")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FaxNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<int?>("StateProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("ZipPostalCode")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("StateProvinceId");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Announcement", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Published")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__City__3214EC07E650DEDE");

                    b.HasIndex("CountryId");

                    b.HasIndex("StateId");

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowsBilling")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowsShipping")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("LimitedToStores")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NumericIsoCode")
                        .HasColumnType("int");

                    b.Property<bool>("Published")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SubjectToVat")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ThreeLetterIsoCode")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("TwoLetterIsoCode")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AdminComment")
                        .HasColumnType("longtext");

                    b.Property<int>("AffiliateId")
                        .HasColumnType("int");

                    b.Property<int?>("BillingAddressId")
                        .HasColumnType("int")
                        .HasColumnName("BillingAddress_Id");

                    b.Property<DateTime?>("CannotLoginUntilDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("EmailToRevalidate")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsSystemAccount")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTaxExempt")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastActivityDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastIpAddress")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastLoginDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("RequireReLogin")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ShippingAddressId")
                        .HasColumnType("int")
                        .HasColumnName("ShippingAddress_Id");

                    b.Property<string>("SystemName")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("Username")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("BillingAddressId");

                    b.HasIndex("ShippingAddressId");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.CustomerAuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("PK_AuthToken");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerAuthToken", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.CustomerPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerPassword", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Download", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("DownloadBinary")
                        .HasColumnType("longblob");

                    b.Property<Guid>("DownloadGuid")
                        .HasColumnType("char(36)");

                    b.Property<int?>("DownloadTypeId")
                        .HasColumnType("int");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Extension")
                        .HasColumnType("longtext");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsNew")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UseDownloadUrl")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Download", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DateChanged")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("PreviewFirst")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SendTo")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Subject")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TemplateHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TemplateHTML");

                    b.HasKey("Id")
                        .HasName("PK_tbl_EmailTemplate");

                    b.ToTable("EmailTemplate", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.FollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FollowUpDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("LeadId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("PK__FollowUp__3214EC0791966B80");

                    b.HasIndex("LeadId");

                    b.ToTable("FollowUp", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.FormResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__FormResp__3214EC07F5A61E02");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FormId");

                    b.ToTable("FormResponses");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.GenericAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOrUpdatedDateUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedOrUpdatedDateUTC");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("KeyGroup")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GenericAttribute", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<string>("LeadName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("LeadSourceId")
                        .HasColumnType("int");

                    b.Property<int>("LeadStatusId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__Lead__3214EC0797DD239A");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LeadSourceId");

                    b.HasIndex("LeadStatusId");

                    b.HasIndex("ProductId");

                    b.ToTable("Lead", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.LeadStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("InputControlType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("InputNotes")
                        .HasColumnType("longtext");

                    b.Property<bool>("InputRequried")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("PreviousStatusId");

                    b.ToTable("LeadStatus", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("FullMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("LogLevelId")
                        .HasColumnType("int");

                    b.Property<string>("PageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("ReferrerUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Log", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Options__3214EC079B8E65DA");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BillingAddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomOrderNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomValuesXml")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerCurrencyCode")
                        .HasColumnType("longtext");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerIp")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("OrderGuid")
                        .HasColumnType("char(36)");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("PickupAddressId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Podate")
                        .HasColumnType("datetime")
                        .HasColumnName("PODate");

                    b.Property<int?>("ShippingAddressId")
                        .HasColumnType("int");

                    b.Property<string>("ShippingMethod")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingRateComputationMethodSystemName")
                        .HasColumnType("longtext");

                    b.Property<string>("VatNumber")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BillingAddressId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PickupAddressId");

                    b.HasIndex("ShippingAddressId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttributeDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderItemGuid")
                        .HasColumnType("char(36)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Style")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Uom")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("UOM");

                    b.Property<string>("Weight")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.OrderNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("DisplayToCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("DownloadId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderNote", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.PagesInRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DateChanged")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tbl_PagesInRoles");

                    b.HasIndex("PageId");

                    b.HasIndex("RoleId");

                    b.ToTable("PagesInRoles");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminComment")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("AvailableEndDateTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("AvailableStartDateTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("CallForPrice")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("FormId")
                        .HasColumnType("int");

                    b.Property<string>("FullDescription")
                        .HasColumnType("longtext");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<bool>("HasUserAgreement")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTaxExempt")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("ProductCost")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("Published")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RedirectUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("longtext");

                    b.Property<bool>("ShowOnHomepage")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Sku")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<int>("TaxCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserAgreementText")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FullDescription")
                        .HasColumnType("longtext");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IncludeInTopMenu")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<int>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("PictureId")
                        .HasColumnType("int");

                    b.Property<bool>("Published")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ShowOnHomepage")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategory", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.ProductCategoryMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsFeaturedProduct")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("Product_Category_Mapping", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SystemKeyword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_NewTable");

                    b.ToTable("ProductType", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Country")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ListingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SquareFeet")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__Property__70C9A755435DB836");

                    b.HasIndex("Country");

                    b.HasIndex("State");

                    b.ToTable("Property", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("ControlType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Question__3214EC07A9DD6067");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.QuestionResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FormResponseId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("PK__Question__3214EC076EA8D706");

                    b.HasIndex("FormResponseId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionResponses");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.ReferenceCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("ReferenceCodeId")
                        .HasColumnType("int");

                    b.Property<int>("ReferenceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("SystemKeyword")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceCodeId");

                    b.HasIndex("ReferenceTypeId");

                    b.ToTable("ReferenceCode", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.ReferenceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("SystemKeyword")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("ReferenceType", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Setting", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.SitePage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DateChanged")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tbl_SitePage");

                    b.ToTable("SitePage", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.StateProvince", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Published")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("StateProvince", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AccessibleWhenStoreClosed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Body")
                        .HasColumnType("longtext");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IncludeInFooterColumn1")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludeInFooterColumn2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludeInFooterColumn3")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludeInSitemap")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IncludeInTopMenu")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPasswordProtected")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LimitedToStores")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("MetaKeywords")
                        .HasColumnType("longtext");

                    b.Property<string>("MetaTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<bool>("Published")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SubjectToAcl")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SystemName")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<int>("TopicTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Topic", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.TopicTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("ViewPath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.HasKey("Id");

                    b.ToTable("TopicTemplate", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Traceability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<int>("ManagerUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("ParentNodeId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_Tracibility");

                    b.HasIndex("ManagerUserId");

                    b.HasIndex("ParentNodeId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("TypeId");

                    b.ToTable("Traceability", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.UrlRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.HasKey("Id");

                    b.ToTable("UrlRecord", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("ParentUserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.UserAuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAuthToken", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.UserPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPassword", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnablePasswordLifetime")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SystemName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_CustomerRole");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("FormQuestionMapping", b =>
                {
                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("FormId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Form_Question_Mapping", (string)null);
                });

            modelBuilder.Entity("ProductFormMapping", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "FormId");

                    b.HasIndex("FormId");

                    b.ToTable("Product_Form_Mapping", (string)null);
                });

            modelBuilder.Entity("RoleAssignment", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("ParentRoleId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "ParentRoleId");

                    b.HasIndex("ParentRoleId");

                    b.ToTable("RoleAssignment", (string)null);
                });

            modelBuilder.Entity("UserRoleMapping", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("Role_Id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK_Customer_CustomerRole_Mapping");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole_Mapping", (string)null);
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.ActivityLog", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.ActivityLogType", "ActivityLogType")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("ActivityLogTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ActivityLog_ActivityLogTypeId_ActivityLogType_Id");

                    b.HasOne("ConnectingDotsAPI.DBModels.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_ActivityLog_User");

                    b.Navigation("ActivityLogType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Address", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.Country", "Country")
                        .WithMany("Addresses")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("FK_Address_CountryId_Country_Id");

                    b.HasOne("ConnectingDotsAPI.DBModels.StateProvince", "StateProvince")
                        .WithMany("Addresses")
                        .HasForeignKey("StateProvinceId")
                        .HasConstraintName("FK_Address_StateProvinceId_StateProvince_Id");

                    b.Navigation("Country");

                    b.Navigation("StateProvince");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.City", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK__City__CountryId__0BB1B5A5");

                    b.HasOne("ConnectingDotsAPI.DBModels.StateProvince", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .IsRequired()
                        .HasConstraintName("FK__City__StateId__0CA5D9DE");

                    b.Navigation("Country");

                    b.Navigation("State");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Customer", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.Address", "BillingAddress")
                        .WithMany("CustomerBillingAddresses")
                        .HasForeignKey("BillingAddressId")
                        .HasConstraintName("FK_Customer_BillingAddress_Id_Address_Id");

                    b.HasOne("ConnectingDotsAPI.DBModels.Address", "ShippingAddress")
                        .WithMany("CustomerShippingAddresses")
                        .HasForeignKey("ShippingAddressId")
                        .HasConstraintName("FK_Customer_ShippingAddress_Id_Address_Id");

                    b.Navigation("BillingAddress");

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.CustomerAuthToken", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.Customer", "Customer")
                        .WithMany("CustomerAuthTokens")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentAuthToken_Student");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.CustomerPassword", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.Customer", "Customer")
                        .WithMany("CustomerPasswords")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentPassword_Student");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.FollowUp", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.Lead", "Lead")
                        .WithMany("FollowUps")
                        .HasForeignKey("LeadId")
                        .HasConstraintName("FK__FollowUp__LeadId__60C757A0");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.FormResponse", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.Customer", "Customer")
                        .WithMany("FormResponses")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_FormResponses_Forms");

                    b.HasOne("ConnectingDotsAPI.DBModels.Form", "Form")
                        .WithMany("FormResponses")
                        .HasForeignKey("FormId")
                        .IsRequired()
                        .HasConstraintName("FK_FormResponses_Forms1");

                    b.Navigation("Customer");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Lead", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.User", "AssignedToNavigation")
                        .WithMany("Leads")
                        .HasForeignKey("AssignedTo")
                        .HasConstraintName("FK_Lead_User");

                    b.HasOne("ConnectingDotsAPI.DBModels.Customer", "Customer")
                        .WithMany("Leads")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_Lead_Customer");

                    b.HasOne("ConnectingDotsAPI.DBModels.ReferenceCode", "LeadSource")
                        .WithMany("Leads")
                        .HasForeignKey("LeadSourceId")
                        .IsRequired()
                        .HasConstraintName("FK_Lead_Source");

                    b.HasOne("ConnectingDotsAPI.DBModels.LeadStatus", "LeadStatus")
                        .WithMany("Leads")
                        .HasForeignKey("LeadStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Lead_LeadStatuses");

                    b.HasOne("ConnectingDotsAPI.DBModels.Product", "Product")
                        .WithMany("Leads")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_Lead_Product");

                    b.Navigation("AssignedToNavigation");

                    b.Navigation("Customer");

                    b.Navigation("LeadSource");

                    b.Navigation("LeadStatus");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.LeadStatus", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.LeadStatus", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_LeadStatus_LeadStatus1");

                    b.HasOne("ConnectingDotsAPI.DBModels.LeadStatus", "PreviousStatus")
                        .WithMany("InversePreviousStatus")
                        .HasForeignKey("PreviousStatusId")
                        .HasConstraintName("FK_LeadStatus_LeadStatus");

                    b.Navigation("Parent");

                    b.Navigation("PreviousStatus");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Log", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.Customer", "Customer")
                        .WithMany("Logs")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Log_CustomerId_Customer_Id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Option", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK__Options__Questio__4277DAAA");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Order", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.Address", "BillingAddress")
                        .WithMany("OrderBillingAddresses")
                        .HasForeignKey("BillingAddressId")
                        .HasConstraintName("FK_Order_BillingAddressId_Address_Id");

                    b.HasOne("ConnectingDotsAPI.DBModels.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_CustomerId_Customer_Id");

                    b.HasOne("ConnectingDotsAPI.DBModels.Address", "PickupAddress")
                        .WithMany("OrderPickupAddresses")
                        .HasForeignKey("PickupAddressId")
                        .HasConstraintName("FK_Order_PickupAddressId_Address_Id");

                    b.HasOne("ConnectingDotsAPI.DBModels.Address", "ShippingAddress")
                        .WithMany("OrderShippingAddresses")
                        .HasForeignKey("ShippingAddressId")
                        .HasConstraintName("FK_Order_ShippingAddressId_Address_Id");

                    b.Navigation("BillingAddress");

                    b.Navigation("Customer");

                    b.Navigation("PickupAddress");

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.OrderItem", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderItem_OrderId_Order_Id");

                    b.HasOne("ConnectingDotsAPI.DBModels.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_OrderItem_ProductId_Product_Id");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.OrderNote", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.Order", "Order")
                        .WithMany("OrderNotes")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderNote_OrderId_Order_Id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.PagesInRole", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.SitePage", "Page")
                        .WithMany("PagesInRoles")
                        .HasForeignKey("PageId")
                        .IsRequired()
                        .HasConstraintName("FK_PagesInRoles_SitePage");

                    b.HasOne("ConnectingDotsAPI.DBModels.UserRole", "Role")
                        .WithMany("PagesInRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_PagesInRoles_CustomerRole");

                    b.Navigation("Page");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Product", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.Form", "Form")
                        .WithMany("Products")
                        .HasForeignKey("FormId")
                        .HasConstraintName("FK_Product_Forms");

                    b.HasOne("ConnectingDotsAPI.DBModels.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Product_ProductType");

                    b.Navigation("Form");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.ProductCategoryMapping", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.ProductCategory", "Category")
                        .WithMany("ProductCategoryMappings")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Product_Category_Mapping_ProductCategory");

                    b.HasOne("ConnectingDotsAPI.DBModels.Product", "Product")
                        .WithMany("ProductCategoryMappings")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_Product_Category_Mapping_Product");

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Property", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.Country", "CountryNavigation")
                        .WithMany("Properties")
                        .HasForeignKey("Country")
                        .IsRequired()
                        .HasConstraintName("FK_Property_Country");

                    b.HasOne("ConnectingDotsAPI.DBModels.StateProvince", "StateNavigation")
                        .WithMany("Properties")
                        .HasForeignKey("State")
                        .IsRequired()
                        .HasConstraintName("FK_Property_StateProvince");

                    b.Navigation("CountryNavigation");

                    b.Navigation("StateNavigation");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.QuestionResponse", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.FormResponse", "FormResponse")
                        .WithMany("QuestionResponses")
                        .HasForeignKey("FormResponseId")
                        .IsRequired()
                        .HasConstraintName("FK_QuestionResponses_QuestionResponses");

                    b.HasOne("ConnectingDotsAPI.DBModels.Question", "Question")
                        .WithMany("QuestionResponses")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_QuestionResponses_Questions");

                    b.Navigation("FormResponse");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.ReferenceCode", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.ReferenceCode", "ReferenceCodeNavigation")
                        .WithMany("InverseReferenceCodeNavigation")
                        .HasForeignKey("ReferenceCodeId")
                        .HasConstraintName("FK_ReferenceCode_ReferenceCode");

                    b.HasOne("ConnectingDotsAPI.DBModels.ReferenceType", "ReferenceType")
                        .WithMany("ReferenceCodes")
                        .HasForeignKey("ReferenceTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_ReferenceCode_ReferenceType");

                    b.Navigation("ReferenceCodeNavigation");

                    b.Navigation("ReferenceType");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.StateProvince", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.Country", "Country")
                        .WithMany("StateProvinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StateProvince_CountryId_Country_Id");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Traceability", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.User", "ManagerUser")
                        .WithMany("TraceabilityManagerUsers")
                        .HasForeignKey("ManagerUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Tracibility_User");

                    b.HasOne("ConnectingDotsAPI.DBModels.Traceability", "ParentNode")
                        .WithMany("InverseParentNode")
                        .HasForeignKey("ParentNodeId")
                        .HasConstraintName("FK_Tracibility_Tracibility");

                    b.HasOne("ConnectingDotsAPI.DBModels.Product", "Product")
                        .WithMany("Traceabilities")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_Tracibility_Product");

                    b.HasOne("ConnectingDotsAPI.DBModels.User", "Supplier")
                        .WithMany("TraceabilitySuppliers")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK_Tracibility_User1");

                    b.HasOne("ConnectingDotsAPI.DBModels.ReferenceCode", "Type")
                        .WithMany("Traceabilities")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Tracibility_ReferenceCode");

                    b.Navigation("ManagerUser");

                    b.Navigation("ParentNode");

                    b.Navigation("Product");

                    b.Navigation("Supplier");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.UserAuthToken", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.User", "User")
                        .WithMany("UserAuthTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserAuthToken_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.UserPassword", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.User", "User")
                        .WithMany("UserPasswords")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserPassword_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormQuestionMapping", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.Form", null)
                        .WithMany()
                        .HasForeignKey("FormId")
                        .IsRequired()
                        .HasConstraintName("FK_Form_Question_Mapping_Forms");

                    b.HasOne("ConnectingDotsAPI.DBModels.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_Form_Question_Mapping_Questions");
                });

            modelBuilder.Entity("ProductFormMapping", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.Form", null)
                        .WithMany()
                        .HasForeignKey("FormId")
                        .IsRequired()
                        .HasConstraintName("FK_Product_Form_Mapping_Forms");

                    b.HasOne("ConnectingDotsAPI.DBModels.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_Product_Form_Mapping_Product");
                });

            modelBuilder.Entity("RoleAssignment", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.UserRole", null)
                        .WithMany()
                        .HasForeignKey("ParentRoleId")
                        .IsRequired()
                        .HasConstraintName("FK_RoleAssignment_UserRole_Parent");

                    b.HasOne("ConnectingDotsAPI.DBModels.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_RoleAssignment_UserRole");
                });

            modelBuilder.Entity("UserRoleMapping", b =>
                {
                    b.HasOne("ConnectingDotsAPI.DBModels.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_Mapping_UserRole");

                    b.HasOne("ConnectingDotsAPI.DBModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_Mapping_User");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.ActivityLogType", b =>
                {
                    b.Navigation("ActivityLogs");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Address", b =>
                {
                    b.Navigation("CustomerBillingAddresses");

                    b.Navigation("CustomerShippingAddresses");

                    b.Navigation("OrderBillingAddresses");

                    b.Navigation("OrderPickupAddresses");

                    b.Navigation("OrderShippingAddresses");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Country", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Cities");

                    b.Navigation("Properties");

                    b.Navigation("StateProvinces");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Customer", b =>
                {
                    b.Navigation("CustomerAuthTokens");

                    b.Navigation("CustomerPasswords");

                    b.Navigation("FormResponses");

                    b.Navigation("Leads");

                    b.Navigation("Logs");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Form", b =>
                {
                    b.Navigation("FormResponses");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.FormResponse", b =>
                {
                    b.Navigation("QuestionResponses");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Lead", b =>
                {
                    b.Navigation("FollowUps");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.LeadStatus", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("InversePreviousStatus");

                    b.Navigation("Leads");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("OrderNotes");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Product", b =>
                {
                    b.Navigation("Leads");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductCategoryMappings");

                    b.Navigation("Traceabilities");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.ProductCategory", b =>
                {
                    b.Navigation("ProductCategoryMappings");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Question", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("QuestionResponses");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.ReferenceCode", b =>
                {
                    b.Navigation("InverseReferenceCodeNavigation");

                    b.Navigation("Leads");

                    b.Navigation("Traceabilities");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.ReferenceType", b =>
                {
                    b.Navigation("ReferenceCodes");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.SitePage", b =>
                {
                    b.Navigation("PagesInRoles");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.StateProvince", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Cities");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.Traceability", b =>
                {
                    b.Navigation("InverseParentNode");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Leads");

                    b.Navigation("TraceabilityManagerUsers");

                    b.Navigation("TraceabilitySuppliers");

                    b.Navigation("UserAuthTokens");

                    b.Navigation("UserPasswords");
                });

            modelBuilder.Entity("ConnectingDotsAPI.DBModels.UserRole", b =>
                {
                    b.Navigation("PagesInRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
